### PR TITLE
deprecated notice

### PR DESCRIPTION
**Pull request by corinnekrych**
AGIOS-402 related
@matzew @cvasilak last PR on the topic
@matzew we'll need removal from travis build too.

### CODE REVIEW

**Comment by matzew** [comment]
before adding this, let's add a branch, with the latest dev - just in case ...

**Comment by corinnekrych** [comment]
+ 1 @matzew wise
let me do it

**Comment by cvasilak** [comment]
since ```dev``` contains the latest ```master```, off you go :+1:

**Comment by matzew** [comment]
:+1: for merging

**Comment by matzew** [comment]
landed

**Pull request merged**
